### PR TITLE
Documentation fix in X509_STORE_CTX_get_error.pod

### PR DESCRIPTION
**Pull request by valcikeric**
I fixed some wrong documentation and changed misspelled error codes. I'm only assuming that these are mistakes, so correct me if I'm wrong.

I divided each change into commits:

44a8c6bcc0 - Fix documentation for X509_V_ERR_CRL_SIGNATURE_FAILURE
- The description of the error identical with X509_V_ERR_CERT_SIGNATURE_FAILURE.

dcdce396ba - Fix X509_V_ERR_CA_KEY_TOO_SMALL (from X509_ERR_CA_KEY_TOO_SMALL)
1eec0bcaa7 - Fix X509_V_ERR_CA_MD_TOO_WEAK (from X509_ERR_CA_KEY_TOO_SMALL)
999001d230 - Fix X509_V_ERR_NO_ISSUER_PUBLIC_KEY (from 509_V_ERROR_NO_ISSUER_PUBLI_KEY)
65d358a643 - Fix X509_V_ERR_SIGNATURE_ALGORITHM_MISMATCH (from X509_V_ERROR_SIGNATURE_ALGORITHM_MISMATCH)
- Replacing error codes to the correct ones in the manual page.

6ffe2e68f7 - Replace commas with colons
- The last two errors had a comma right after the error code, every other error has a colon. Changed for consistency.

### CODE REVIEW

**Comment by valcikeric** [comment]
@mukrop @zacikpa

**Comment by mukrop** [comment]
Nice! Some comments:
* Have a better branch name than "pr" (try to think of something simple that at least coarsely conveys what is the PR about).
* PR name: The filename does not need to be mentioned (that is easy to see in the "files changed" tab). Which leaves us with "documentation fix". What kind of documentation fix is it? (What does it concern?)
* First paragraph: First sentence OK, the second is a bit timid (though respect is appropriate, that's true!).
* Division into commits: OK. Maybe a bit too detailed to my taste. It's not necessary to split by individual errors, rather by logical parts. If they like the CRL fix, they may still not like the error code change (it's a different change). Though it's quite improbable they will want just some error code changes and not others. I would thus suggest three commits: The first you have, then the main block of error codes and then the typographical consistency.
* CRL signature docs: Be a bit more precise. True, the description of the error code is the same as the other, but where's the problem? (Mention this error is related to CRLs and not certificates.)
* Error code changes: A bit more details here, please. It's unintuitive why would you change the error code. Do the basic explanation linking to the error code definition file in code demonstrating that the code names are wrong (possibly even with line numbers). Ideally, use blame to find the commit where the change was made to the code (and forgotten to be done in the docs) and mention the commit. Think from the point of the maintainer doing the approval: They have plenty of work, let's make it as easy to them as possible to see that it's actually a mistake.
* Typographical consistency: Nice description, no objections.
* The individual commits should have meaningful commit messages. When merged, the commit messages should explain the changes in the main code trunk (the PR discussion will be forgotten). Thus, the points above should be explained sufficiently in the commit messages as well. It's OK to have the PR description nearly just as a concatenation of the commit messages (just to illustrate how much detail I expect in the commit messages). Imagine that is the main place for reasoning (use case: if a future you/another dev will use blame to look for change rationale, they will see the commit message only).
* Let's go with a bit of PR and mention it's small bug we found while doing research on better error documentation as discussed in the [openssl-project mailing list](https://mta.openssl.org/pipermail/openssl-project/2020-March/001882.html).
* I suggest you re-do the pull request here first (will also work as a nice git exercise :-P).
* Great work, keep it up! :-)

**Comment by valcikeric** [comment]
Thank you for the feedback. I'll create a new pull request and again tag you both in it.

**Comment by mukrop** [comment]
Or just force-push in this one (though the branch name change will probably force you to make a new one).

**Pull request closed without merging**
